version: "3.9"

services:
  site:
    build: .
    image: conjurer/richallen.info:latest
    command: bundle exec jekyll serve --trace --host 0.0.0.0 --watch --incremental --port 4002
    environment:
      - JEKYLL_ENV=development
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4002:4002
